spring:
  zipkin:
  datasource:
    #url: "jdbc:postgresql://localhost:5432/card_allocation_service?createDatabaseIfNotExist=true"
    shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    #username: postgres
    #password: rootPassword
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true